name: Shortcut (Clubhouse) Workflow
description: Updates and transitions the workflow state of shortcut stories
branding:
  icon: chevrons-right
  color: orange
inputs:
  clubhouseToken:
    description: auth token for clubhouse api
    required: true
  githubToken:
    description: github auth token for api access
    required: true
  endStateName:
    description: name of the workflow state stories should be transisitioned to
    required: false
    default: Completed
  addReleaseInfo:
    description: update story descriptions with link to github release
    required: false
    default: "false"
outputs:
  updatedStories:
    description: An array of the story names that were updated
runs:
  using: node18
  main: dist/index.js
