name: e2e test
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  update-clubhouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: action

      - uses: ./action
        with:
          clubhouseToken: ${{ secrets.CLUBHOUSE_TOKEN }}
          endStateName: 'In Review'
